### ISSUE TITLE
createHashHistory throws in a React Native environment

### ISSUE THREAD

**Issue by pigoz** [gcanti/elm-ts#14]
`createHashHistory` which is called here https://github.com/gcanti/elm-ts/blob/master/src/Navigation.ts#L15 throws in React Native. It may be a good idea to not import `Navigation.ts` in `index.ts`?

**Comment by minedeljkovic** [comment]
`Navigation` could be moved to separate package, and leave other core modules here and that would work perfectly with React Native. @gcanti what is your opinion on this?

P.S. `react-dom` is already unnecessary dependency, since [this change](https://github.com/gcanti/elm-ts/commit/3ecc7de13693f252ab24fe736e1dcb58493ffafe#diff-810d50de0612958b62cde9634243f151)

**Comment by gcanti** [comment]
I agree to 

- not import the `Navigation` module in `index` (in the next breaking change release) 
- remove the useless dependency (asap)

**Comment by StefanoMagrassi** [comment]
resolved in 062460d7a24add0d262cf1e41f320a04b871d554
