### ISSUE TITLE
How to decode a 204?

### ISSUE THREAD

**Issue by bmazzarol** [gcanti/elm-ts#46]
Hi Guys,

This is a question which I hope you can help me with.

With a 204 response there is no response body to decode, as far as I can tell the current code always requires a decoder, therefor assumes there is always a body and JSON.parse will fail. https://github.com/gcanti/elm-ts/blob/master/src/Http.ts#L153

Is there a NoOp decoder or something?

At the moment I'm just getting the server to return an empty object.

Any help would be fantastic. I need to be able to handle spec compliant responses.

**Comment by StefanoMagrassi** [comment]
Hi @bmazzarol 

it looks like you found a bug!

I think that we can fix it with something like `@contactlab/appy`'s [`parseResponse`](https://github.com/contactlab/appy/blob/master/src/combinators/decoder.ts#L78) in `withDecoder` combinator.

This is my proposal:

- `response.body` is always a string (because of `responseType: 'text'` field in [`Request`](https://github.com/gcanti/elm-ts/blob/master/src/Http.ts#L136))
- instead of always try to parse it as JSON, when body is an empty string (that is spec compliant), we can "remap" it to `'{}'` (literal) which will be parsed to a valid empty JSON object
- then you can provide an "empty" decoder that fits this specific case

An "empty decoder" could be something like this:
```ts
import {Decoder} from 'elm-ts/lib/Decode';
import * as E from 'fp-ts/lib/Either';

export const Empty: Decoder<{}> = u =>
  typeof u === 'object' && u !== null && Object.keys(u).length === 0 ? E.right(u) : E.left`"${u}" should be an empty object`')
```

Or using `io-ts`:
```ts
import {Decoder} from 'elm-ts/lib/Decode';
import * as t from 'io-ts'
import { failure } from 'io-ts/lib/PathReporter'

function fromCodec<A>(codec: t.Decoder<unknown, A>): Decoder<A> {
  return flow(
    codec.decode,
    E.mapLeft(errors => failure(errors).join('\n'))
  )
}

export const Empty: Decoder<{}> = fromCodec(t.type({}))
```

**Comment by bmazzarol** [comment]
Hi @StefanoMagrassi,

Thanks for the response.

I have run with it and created a PR that implements the linked logic for empty responses.

I also exposed a function to send a request and get a full response back, this allows for access to the response headers, a requirement when working the ETags and correlation ids.

Let me know what you think. 

The empty decoder with IO-TS works!
